name: Build, Test, and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Verify TypeScript installation
        run: npx tsc -v

      - name: Build TypeScript
        run: npm run build

#     - name: Run tests
#       run: npm test

#      - name: Validate scenes
#        run: npm run validate:scenes

      - name: Clean unnecessary files
        run: |
          rm -rf src node_modules
          echo "🧹 Cleaned build folder (keeping compiled JS only)."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
 
