name: Validate Scenes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-scenes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --include=dev

      - name: Run Scene Validator
        run: npm run validate:scenes
